INSERT INTO criterios_puntuacion (nombre_criterio, fase, puntos) VALUES
('Marcador Completo','Fase de Grupos',10),
('Marcador Completo','Dieciseisavos',20),
('Marcador Completo','Octavos',30),
('Marcador Completo','Cuartos',40),
('Marcador Completo','Semifinal',50),
('Marcador Completo','Tercer Puesto',60),
('Marcador Completo','Final',70),
('Acierto de Empate','Fase de Grupos',6),
('Acierto de Empate','Dieciseisavos',12),
('Acierto de Empate','Octavos',18),
('Acierto de Empate','Cuartos',24),
('Acierto de Empate','Semifinal',30),
('Acierto de Empate','Tercer Puesto',36),
('Acierto de Empate','Final',42),
('Acierto de Marcador Inverso','Fase de Grupos',3),
('Acierto de Marcador Inverso','Dieciseisavos',6),
('Acierto de Marcador Inverso','Octavos',9),
('Acierto de Marcador Inverso','Cuartos',12),
('Acierto de Marcador Inverso','Semifinal',15),
('Acierto de Marcador Inverso','Tercer Puesto',18),
('Acierto de Marcador Inverso','Final',21),
('Solo acierto de ganador','Fase de Grupos',3),
('Solo acierto de ganador','Dieciseisavos',6),
('Solo acierto de ganador','Octavos',9),
('Solo acierto de ganador','Cuartos',12),
('Solo acierto de ganador','Semifinal',15),
('Solo acierto de ganador','Tercer Puesto',18),
('Solo acierto de ganador','Final',21),
('Solo diferencia de goles directa','Fase de Grupos',3),
('Solo diferencia de goles directa','Dieciseisavos',6),
('Solo diferencia de goles directa','Octavos',9),
('Solo diferencia de goles directa','Cuartos',12),
('Solo diferencia de goles directa','Semifinal',15),
('Solo diferencia de goles directa','Tercer Puesto',18),
('Solo diferencia de goles directa','Final',21),
('Solo diferencia de goles inversa','Fase de Grupos',1),
('Solo diferencia de goles inversa','Dieciseisavos',2),
('Solo diferencia de goles inversa','Octavos',3),
('Solo diferencia de goles inversa','Cuartos',4),
('Solo diferencia de goles inversa','Semifinal',5),
('Solo diferencia de goles inversa','Tercer Puesto',6),
('Solo diferencia de goles inversa','Final',7),
('Solo medio marcador','Fase de Grupos',1),
('Solo medio marcador','Dieciseisavos',2),
('Solo medio marcador','Octavos',3),
('Solo medio marcador','Cuartos',4),
('Solo medio marcador','Semifinal',5),
('Solo medio marcador','Tercer Puesto',6),
('Solo medio marcador','Final',7),
('Acierto ganador y diferencia directa','Fase de Grupos',6),
('Acierto ganador y diferencia directa','Dieciseisavos',12),
('Acierto ganador y diferencia directa','Octavos',18),
('Acierto ganador y diferencia directa','Cuartos',24),
('Acierto ganador y diferencia directa','Semifinal',30),
('Acierto ganador y diferencia directa','Tercer Puesto',36),
('Acierto ganador y diferencia directa','Final',42),
('Acierto de ganador y medio marcador','Fase de Grupos',4),
('Acierto de ganador y medio marcador','Dieciseisavos',8),
('Acierto de ganador y medio marcador','Octavos',12),
('Acierto de ganador y medio marcador','Cuartos',16),
('Acierto de ganador y medio marcador','Semifinal',20),
('Acierto de ganador y medio marcador','Tercer Puesto',24),
('Acierto de ganador y medio marcador','Final',28),
('Medio marcador y diferencia inversa','Fase de Grupos',2),
('Medio marcador y diferencia inversa','Dieciseisavos',4),
('Medio marcador y diferencia inversa','Octavos',6),
('Medio marcador y diferencia inversa','Cuartos',8),
('Medio marcador y diferencia inversa','Semifinal',10),
('Medio marcador y diferencia inversa','Tercer Puesto',12),
('Medio marcador y diferencia inversa','Final',14);
